In [1]:
import pandas as pd 
import numpy as np
from sklearn import preprocessing 
from sklearn.preprocessing import MinMaxScaler 

In [2]:
sales_data = pd.read_csv("sales_2019.csv")

In [3]:
sales_data.head()

Order ID                   Product  Quantity Ordered  Price Each  \
0    141234                    iPhone                 1      700.00   
1    141235  Lightning Charging Cable                 1       14.95   
2    141236          Wired Headphones                 2       11.99   
3    141237          27in FHD Monitor                 1      149.99   
4    141238          Wired Headphones                 1       11.99   

        Order Date                       Purchase Address  
0  1/22/2019 21:25        944 Walnut St, Boston, MA 02215  
1  1/28/2019 14:15       185 Maple St, Portland, OR 97035  
2  1/17/2019 13:33  538 Adams St, San Francisco, CA 94016  
3   1/5/2019 20:33     738 10th St, Los Angeles, CA 90001  
4  1/25/2019 11:59          387 10th St, Austin, TX 73301

In [4]:
label_encoder = preprocessing.LabelEncoder()
sales_data['Product'] = label_encoder.fit_transform(sales_data['Product'])
sales_data['Product'].unique()

array([18, 12, 17,  2,  5,  1, 15,  7,  6, 13,  8, 16,  4,  9,  0,  3, 14,
       10, 11])

In [6]:
sales_data['City'] = sales_data['Purchase Address'].str.split(',').str[1]
sales_data['State'] = sales_data['Purchase Address'].str.split(',').str[2]

In [7]:
print(sales_data)

        Order ID  Product  Quantity Ordered  Price Each        Order Date  \
0         141234       18                 1      700.00   1/22/2019 21:25   
1         141235       12                 1       14.95   1/28/2019 14:15   
2         141236       17                 2       11.99   1/17/2019 13:33   
3         141237        2                 1      149.99    1/5/2019 20:33   
4         141238       17                 1       11.99   1/25/2019 11:59   
...          ...      ...               ...         ...               ...   
185945    319666       12                 1       14.95  12/11/2019 20:58   
185946    319667        4                 2        3.84   12/1/2019 12:01   
185947    319668       16                 1      400.00    12/9/2019 6:43   
185948    319669       17                 1       11.99   12/3/2019 10:39   
185949    319670        7                 1       99.99  12/21/2019 21:45   

                              Purchase Address            City      State  

In [8]:
sales_data['State'] = sales_data['State'].str.replace('\d+', '')

C:\Users\16096\AppData\Local\Temp\ipykernel_3920\1452098177.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  sales_data['State'] = sales_data['State'].str.replace('\d+', '')


In [9]:
print(sales_data)

        Order ID  Product  Quantity Ordered  Price Each        Order Date  \
0         141234       18                 1      700.00   1/22/2019 21:25   
1         141235       12                 1       14.95   1/28/2019 14:15   
2         141236       17                 2       11.99   1/17/2019 13:33   
3         141237        2                 1      149.99    1/5/2019 20:33   
4         141238       17                 1       11.99   1/25/2019 11:59   
...          ...      ...               ...         ...               ...   
185945    319666       12                 1       14.95  12/11/2019 20:58   
185946    319667        4                 2        3.84   12/1/2019 12:01   
185947    319668       16                 1      400.00    12/9/2019 6:43   
185948    319669       17                 1       11.99   12/3/2019 10:39   
185949    319670        7                 1       99.99  12/21/2019 21:45   

                              Purchase Address            City State  
0   

In [10]:
sales_data['City'] = label_encoder.fit_transform(sales_data['City'])
sales_data['City'].unique()

array([2, 6, 7, 4, 1, 0, 8, 5, 3])

In [11]:
sales_data['State'] = label_encoder.fit_transform(sales_data['State'])
sales_data['State'].unique()

array([2, 5, 0, 6, 1, 7, 4, 3])

In [12]:
sales_data.drop('Purchase Address', axis=1, inplace=True)

In [13]:
print(sales_data)

        Order ID  Product  Quantity Ordered  Price Each        Order Date  \
0         141234       18                 1      700.00   1/22/2019 21:25   
1         141235       12                 1       14.95   1/28/2019 14:15   
2         141236       17                 2       11.99   1/17/2019 13:33   
3         141237        2                 1      149.99    1/5/2019 20:33   
4         141238       17                 1       11.99   1/25/2019 11:59   
...          ...      ...               ...         ...               ...   
185945    319666       12                 1       14.95  12/11/2019 20:58   
185946    319667        4                 2        3.84   12/1/2019 12:01   
185947    319668       16                 1      400.00    12/9/2019 6:43   
185948    319669       17                 1       11.99   12/3/2019 10:39   
185949    319670        7                 1       99.99  12/21/2019 21:45   

        City  State  
0          2      2  
1          6      5  
2        

In [14]:
sales_data['Month'] = sales_data['Order Date'].str.split('/').str[0]
sales_data['Time'] = sales_data['Order Date'].str.split(' ').str[1]

In [15]:
print(sales_data)

        Order ID  Product  Quantity Ordered  Price Each        Order Date  \
0         141234       18                 1      700.00   1/22/2019 21:25   
1         141235       12                 1       14.95   1/28/2019 14:15   
2         141236       17                 2       11.99   1/17/2019 13:33   
3         141237        2                 1      149.99    1/5/2019 20:33   
4         141238       17                 1       11.99   1/25/2019 11:59   
...          ...      ...               ...         ...               ...   
185945    319666       12                 1       14.95  12/11/2019 20:58   
185946    319667        4                 2        3.84   12/1/2019 12:01   
185947    319668       16                 1      400.00    12/9/2019 6:43   
185948    319669       17                 1       11.99   12/3/2019 10:39   
185949    319670        7                 1       99.99  12/21/2019 21:45   

        City  State Month   Time  
0          2      2     1  21:25  
1    

In [16]:
sales_data.drop('Order Date', axis=1, inplace=True)

In [17]:
print(sales_data)

        Order ID  Product  Quantity Ordered  Price Each  City  State Month  \
0         141234       18                 1      700.00     2      2     1   
1         141235       12                 1       14.95     6      5     1   
2         141236       17                 2       11.99     7      0     1   
3         141237        2                 1      149.99     4      0     1   
4         141238       17                 1       11.99     1      6     1   
...          ...      ...               ...         ...   ...    ...   ...   
185945    319666       12                 1       14.95     7      0    12   
185946    319667        4                 2        3.84     4      0    12   
185947    319668       16                 1      400.00     8      7    12   
185948    319669       17                 1       11.99     3      6    12   
185949    319670        7                 1       99.99     4      0    12   

         Time  
0       21:25  
1       14:15  
2       13:33  

In [18]:
sales_data['Hour'] = sales_data['Time'].str.split(':').str[0]
sales_data['Minute'] = sales_data['Time'].str.split(':').str[1]

In [19]:
sales_data.drop('Time', axis=1, inplace=True)

In [20]:
print(sales_data)

        Order ID  Product  Quantity Ordered  Price Each  City  State Month  \
0         141234       18                 1      700.00     2      2     1   
1         141235       12                 1       14.95     6      5     1   
2         141236       17                 2       11.99     7      0     1   
3         141237        2                 1      149.99     4      0     1   
4         141238       17                 1       11.99     1      6     1   
...          ...      ...               ...         ...   ...    ...   ...   
185945    319666       12                 1       14.95     7      0    12   
185946    319667        4                 2        3.84     4      0    12   
185947    319668       16                 1      400.00     8      7    12   
185948    319669       17                 1       11.99     3      6    12   
185949    319670        7                 1       99.99     4      0    12   

       Hour Minute  
0        21     25  
1        14     15  


In [25]:
train = sales_data.loc[sales_data.index < 139461]
test = sales_data.loc[sales_data.index >= 139461]

print(len(train),len(test))

139461 46489


In [26]:
scaler = MinMaxScaler()
print(scaler.fit(sales_data))

MinMaxScaler()


In [27]:
print(scaler.data_max_)

[3.1967e+05 1.8000e+01 9.0000e+00 1.7000e+03 8.0000e+00 7.0000e+00
 1.2000e+01 2.3000e+01 5.9000e+01]


In [28]:
print(scaler.transform(sales_data))

[[0.00000000e+00 1.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  9.13043478e-01 4.23728814e-01]
 [5.60425026e-06 6.66666667e-01 0.00000000e+00 ... 0.00000000e+00
  6.08695652e-01 2.54237288e-01]
 [1.12085005e-05 9.44444444e-01 1.25000000e-01 ... 0.00000000e+00
  5.65217391e-01 5.59322034e-01]
 ...
 [9.99988791e-01 8.88888889e-01 0.00000000e+00 ... 1.00000000e+00
  2.60869565e-01 7.28813559e-01]
 [9.99994396e-01 9.44444444e-01 0.00000000e+00 ... 1.00000000e+00
  4.34782609e-01 6.61016949e-01]
 [1.00000000e+00 3.88888889e-01 0.00000000e+00 ... 1.00000000e+00
  9.13043478e-01 7.62711864e-01]]
